// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegYoWlJQy7O4zBnIBFsZ4x63FuFXv6fE',
    appId: '1:613549416080:web:510d0ba143aba789fd8215',
    messagingSenderId: '613549416080',
    projectId: 'smart-formation-3acb1',
    authDomain: 'smart-formation-3acb1.firebaseapp.com',
    storageBucket: 'smart-formation-3acb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAhhDbaaKKKowF_xc3ZwGLfhOq7800II',
    appId: '1:613549416080:android:2f9dee6a9d7200c3fd8215',
    messagingSenderId: '613549416080',
    projectId: 'smart-formation-3acb1',
    storageBucket: 'smart-formation-3acb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6gumX-l9Bp95Dd_-P44Hn7Q9gMIJVRc',
    appId: '1:613549416080:ios:c2f1dd9f54edb959fd8215',
    messagingSenderId: '613549416080',
    projectId: 'smart-formation-3acb1',
    storageBucket: 'smart-formation-3acb1.appspot.com',
    iosBundleId: 'com.example.smartFormation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD6gumX-l9Bp95Dd_-P44Hn7Q9gMIJVRc',
    appId: '1:613549416080:ios:767a676151e4f205fd8215',
    messagingSenderId: '613549416080',
    projectId: 'smart-formation-3acb1',
    storageBucket: 'smart-formation-3acb1.appspot.com',
    iosBundleId: 'com.example.smartFormation.RunnerTests',
  );
}
